#! /bin/zsh

# Iterate over dein managed repositories looking for modifications.
#
# The primary use of this script is to hunt out quick hacks that have been made
# to repositories that may have been forgotten about.
#
# Use -s to display just the repository name.

for d (${XDG_CACHE_HOME:-~/.cache}/vim/dein/repos/github.com/*/*(/)) {
    cd $d
    if git status -s | grep -q '^.M'; then
        if [[ $1 == -s ]] {
            echo $d:h:t/$d:t
        } else {
            print -D $d
        }
    fi
}
